# Generated by Django 5.2.4 on 2025-08-31 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='report',
            old_name='photo_url',
            new_name='title',
        ),
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='report',
            name='predicted_report_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='geotag_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='geotag_long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='webapp.user'),
        ),
        migrations.AlterField(
            model_name='userreward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rewards', to='webapp.user'),
        ),
        migrations.AlterUniqueTogether(
            name='userreward',
            unique_together={('user', 'reward')},
        ),
    ]
